; Ch3 Programming Exercise 6: AddVariables Program
; Modify the AddVariables program so it uses 64-bit variables. Describe the
; syntax errors generated by the assembler and what steps you took to
; resolve the errors.
;
; [겪은 오류와 해결 과정]
; 1차 시도: 변수를 QWORD로 바꾸고 그대로 32비트 레지스터로 더하려 했음
;   var1 QWORD 1000h
;   var2 QWORD 2000h
;   ...
;   mov eax, var1      ; error A2022: instruction operand must be the same size
;                        (EAX는 32비트 레지스터인데 var1은 64비트 QWORD라서 크기 불일치)
;   add eax, var2       ; 같은 이유로 오류
;
; 원인: 이 프로젝트는 Irvine32(32비트 보호모드) 라이브러리를 사용하므로
;       RAX 같은 64비트 범용 레지스터 자체를 사용할 수 없다(32비트 모드의 한계).
;
; 해결: 64비트 값을 상위 32비트(high dword)와 하위 32비트(low dword) 두 개로
;       나누어 32비트 레지스터로 각각 더하고, 하위 덧셈에서 발생한 캐리를
;       ADC(Add with Carry) 명령으로 상위 덧셈에 반영하는 방식으로 처리했다.

INCLUDE Irvine32.inc

.data
var1 QWORD 100000000h      ; 64비트 변수 1 (0x1_0000_0000)
var2 QWORD 200000000h      ; 64비트 변수 2 (0x2_0000_0000)
sum  QWORD ?                ; 64비트 합계 저장 변수

.code
main PROC
    ; 하위 32비트(low dword)끼리 먼저 더한다
    mov eax, DWORD PTR var1          ; var1의 하위 32비트 로드
    add eax, DWORD PTR var2           ; var2의 하위 32비트를 더함 (여기서 캐리 발생 가능)
    mov DWORD PTR sum, eax             ; 결과의 하위 32비트 저장

    ; 상위 32비트(high dword)는 ADC로 더해서 하위 덧셈의 캐리를 반영한다
    mov eax, DWORD PTR [var1+4]        ; var1의 상위 32비트 로드
    adc eax, DWORD PTR [var2+4]        ; var2의 상위 32비트 + 이전 캐리
    mov DWORD PTR [sum+4], eax          ; 결과의 상위 32비트 저장

    ; 결과 출력 (하위 32비트만 간단히 확인용으로 출력)
    mov eax, DWORD PTR sum
    call WriteHex
    call Crlf

    invoke ExitProcess, 0
main ENDP
END main
